---
title: "Gas Price Tracker"
author: "Author: Brian Seko"
date: "Last Updated: `r format(Sys.Date(), '%B %d, %Y')`"
output: html_document
params:
  db_file: "/database/gas_data.db"
---

<style>
body {
  text-align: left;
}
.main-container {
  margin-left: auto;
  margin-right: 500px;
  max-width: 1000px; /* Adjust as needed */
}
</style>

```{r setup, include=FALSE}
library(DBI)
library(RSQLite) 
library(tidyverse)
library(here)
library(lubridate)
library(ggplot2)
library(TSstudio)
library(plotly)
library(stargazer)
library(glue)
library(tsibble)
library(forecast)
library(scales)
library(zoo)

knitr::opts_chunk$set(echo = FALSE, fig.show='asis')

current_date <- Sys.Date()
current_month <- month(Sys.Date())
first_day_of_current_month <- as.Date(format(current_date, "%Y-%m-01"))
```

```{r connect to gas forecasting database}
con <- dbConnect(RSQLite::SQLite(), paste0(here(),params$db_file))
gas_raw <- dbGetQuery(con, "select * from gas_prices")
```

```{r Describe Average by Month}
gas_monthly_average <- gas_raw %>% 
  mutate(year = year(period), month=month(period), period_month=as.Date(paste0(year,"-", month, "-01"))) %>% 
  filter(period_month < first_day_of_current_month) %>% #only show complete months
  group_by(period_month, padd) %>% 
  summarise(monthly_average = round(mean(price),2), .groups = "drop") %>% 
  mutate(
    padd_descrip = case_when(
      padd=="PADD 1" ~"East Coast",
      padd=="PADD 2" ~"Midwest", 
      padd=="PADD 3" ~"Gulf Coast",
      padd=="PADD 4" ~"Rocky Mountain",
      TRUE ~"West Coast"),
  ) %>% select(-padd)

gas_national_average <- gas_raw %>% 
  mutate(year = year(period), month=month(period), period_month=as.Date(paste0(year,"-", month, "-01"))) %>% 
  filter(as.Date(period_month) < first_day_of_current_month) %>% 
  group_by(period_month) %>% 
  summarise(monthly_average = round(mean(price),2), .groups = "drop") %>% 
  mutate(padd_descrip="National (All Regions)")

gas_monthly_average_w_national <- rbind(gas_monthly_average,gas_national_average)
```

```{r Average Gas Price per Month Plot, fig.width=13, fig.height=6}
gas_over_time_plot <- ggplot(data = gas_monthly_average_w_national, aes(x = period_month, y=monthly_average))+
  geom_line(aes(color = padd_descrip))+
  theme_minimal()+
  scale_x_date(date_breaks = "5 years", date_labels="%Y")+
  scale_y_continuous(breaks = seq(0,ceiling(max(gas_monthly_average_w_national$monthly_average)), by = 1),
                     limits = c(0, NA)) +
  labs(y="Dollars", x="", color = "Region", title="Average Gas Price per Month")

ggplotly(gas_over_time_plot)
```

```{r Average Gas Price per Month Plot: Last 6 Months, fig.width=13, fig.height=6}
date_filter <- Sys.Date() %m-% months(6)

gas_over_time_plot <- ggplot(data = gas_monthly_average_w_national %>% 
                               filter(period_month>date_filter), aes(x = period_month, y=monthly_average))+
  geom_line(aes(color = padd_descrip))+
  theme_minimal()+
  scale_x_date(date_breaks = "1 months", date_labels="%B %Y")+
  scale_y_continuous(breaks = seq(0,ceiling(max(gas_monthly_average_w_national$monthly_average)), by = 1),
                     limits = c(0, NA)) +
  labs(y="Dollars", x="", color = "Region", title="Average Gas Price per Month: Past 6 Months")

ggplotly(gas_over_time_plot)
```

```{r Average Gas Price, Last Month by Year, fig.width=13, fig.height=6}
last_month <- current_month-1
last_month_name <- format(Sys.Date() %m-% months(1), '%B')

last_month_national_average <- gas_monthly_average_w_national %>% 
  filter(month(period_month) == last_month, padd_descrip == "National (All Regions)", period_month>Sys.Date() %m-% years(10)) %>% 
  mutate(year = year(period_month))

gas_month_comparison_plot <- ggplot(data = last_month_national_average)+
  geom_bar(aes(x=year, y=monthly_average), stat="identity", fill = '#007bff')+
  theme_minimal()+
  scale_x_continuous(breaks = seq(min(last_month_national_average$year), max(last_month_national_average$year), by = 1))+
  labs(x = "Year", y = "Monthly Average", title = glue("{last_month_name} Over Time"))

ggplotly(gas_month_comparison_plot)
```


```{r Average Gas Price per Month Plot Recent Year Focus, fig.width=13, fig.height=6}
yearly_average <- gas_raw %>% 
  mutate(year = year(period), month=month(period), period_month=as.Date(paste0(year,"-", month, "-01"))) %>% 
  filter(as.Date(period_month) < first_day_of_current_month) %>% 
  group_by(year) %>% 
  summarise(yearly_average = round(mean(price),2), .groups = "drop")

trend_recent_years <- gas_monthly_average_w_national %>% 
  filter(year(period_month)>=2020, padd_descrip=="National (All Regions)") %>% 
  mutate(year = year(period_month)) %>% 
  left_join(yearly_average, by="year")

gas_over_time_plot_recent <- ggplot(data = trend_recent_years, aes(x = period_month, y=monthly_average))+
  geom_line(aes(color = "Monthly Average"), linewidth=0.75)+
  geom_line(aes(y=yearly_average, color="Yearly Average"), linewidth=0.75)+
  geom_vline(xintercept = as.Date("2021-01-01"), linetype = "dashed", color = "blue") +
  geom_vline(xintercept = as.Date("2022-01-01"), linetype = "dashed", color = "blue") +
  geom_vline(xintercept = as.Date("2023-01-01"), linetype = "dashed", color = "blue") +
  theme_minimal()+
  scale_x_date(date_breaks = "6 months", date_labels="%m/%y")+
  scale_y_continuous(breaks = seq(0,ceiling(max(trend_recent_years$monthly_average)), by = 1),
                     limits = c(0, NA)) +
  labs(y="Dollars", x="", color = "", title="National Average Gas Price per Month: 2020-YTD")+
  theme(text = element_text(size = 14), # Set all text size to 14
        axis.title = element_text(size = 14), # Set axis titles size to 14
        axis.text = element_text(size = 14), # Set axis text size to 14
        plot.title = element_text(size = 14))

ggplotly(gas_over_time_plot_recent)
```

```{r Trend over the past few weeks, fig.width=13, fig.height=6}

cutoff <- Sys.Date() %m-% months(6)

trend_data_weeks <- trend_recent_years %>% 
  filter(as.Date(period_month)>=as.Date(cutoff)) %>% 
  mutate(text_pos = monthly_average-.25)

gas_over_time_plot_recent_weeks <- ggplot(data = trend_data_weeks, aes(x = as.Date(period_month), y=monthly_average))+
  geom_line(aes(color = "Monthly Average"), linewidth=0.75)+
  geom_line(aes(y=yearly_average, color="Yearly Average"), linewidth=0.75)+
  geom_point(aes(color = "Monthly Average"))+
  geom_text(aes(y = text_pos, label=monthly_average, color = "Monthly Average"), vjust=1.5, show.legend = FALSE)+
  theme_minimal()+
  scale_x_date(date_breaks = "1 months", date_labels="%m/%y")+
  scale_y_continuous(breaks = seq(0,ceiling(max(trend_recent_years$monthly_average)), by = 1),
                     limits = c(0, NA)) +
  labs(y="Dollars", x="", color = "", title="National Average Gas Price: Past 6 Months")+
  theme(text = element_text(size = 14), # Set all text size to 14
        axis.title = element_text(size = 14), # Set axis titles size to 14
        axis.text = element_text(size = 14), # Set axis text size to 14
        plot.title = element_text(size = 14))
  
ggplotly(gas_over_time_plot_recent_weeks)
```

```{r Yearly Averages Compared, fig.width=13, fig.height=6}
yearly_avg_compared <- gas_monthly_average_w_national %>% 
  mutate(year = year(period_month)) %>% 
  filter(year>=year(Sys.Date())-15, padd_descrip=="National (All Regions)") %>% 
  group_by(year) %>% 
  summarise(yearly_average = mean(monthly_average), .groups="drop")

yearly_avg_compared_plot <- ggplot(data=yearly_avg_compared, aes(x=year))+
  geom_bar(aes(y=yearly_average), stat="identity", fill = "#007bff")+
  theme_minimal()+
  theme(panel.grid.minor = element_blank())+
  scale_x_continuous(breaks=seq(min(yearly_avg_compared$year), max(yearly_avg_compared$year), by = 1))+
  labs(x="Dollars", y="", title="Yearly Averages Compared: National Average Price")
  
ggplotly(yearly_avg_compared_plot)
```



```{r Price Distribution,  fig.width=13, fig.height=6}
dist_plot_data <- gas_monthly_average_w_national %>%
  mutate(year = year(period_month)) %>%
  filter(year %in% c(2021, 2022, 2023))

price_dist_plot <- ggplot(dist_plot_data, aes(x = monthly_average, fill = as.factor(year))) +
  geom_density(alpha = 0.5) +  # Adjust alpha for transparency
  facet_wrap(~padd_descrip) +
  scale_fill_brewer(palette = "Set1") +
  scale_x_continuous(breaks = seq(floor(min(dist_plot_data$monthly_average)), ceiling(max(dist_plot_data$monthly_average)), by = 0.5)) +
  theme_minimal() +
  theme(panel.spacing = unit(1, "lines")) +
  labs(title="Price Distribution by Year by Region", fill = "Year", x = "Monthly Average", y = "Density")

ggplotly(price_dist_plot)#, width = 1000, height = 500)
```

```{r Seasonality Analysis, fig.width=10, fig.height=8}
ts_national_df <- gas_monthly_average_w_national %>%
  filter(padd_descrip == "National (All Regions)", period_month>Sys.Date() %m-% years(10)) %>%
  arrange(period_month) %>% 
  mutate(year = year(period_month), month = month(period_month))

ts_national <- ts(ts_national_df %>% pull(monthly_average), start = c(2014, 3), frequency = 12)

ggplot(ts_national_df, aes(x = monthly_average, fill = as.factor(month))) +
  geom_density(alpha = 0.5) +  # Adjust alpha for transparency if desired
  facet_grid(rows = vars(as.factor(month))) +  # Use facet_grid to layout plots in a grid
  theme_minimal() +
  labs(x = "Monthly Average", y = "Density", title = "Density Plot by Month for National Monthly Average", fill = "Month") +
  theme(strip.text.y = element_text(angle = 0))  # Rotate the facet labels for better readability


```

```{r National Average Seasonal Gas Price Trends, fig.width=13, fig.height=6}
national_trend_polt <- ggseasonplot(ts_national)+
  theme_minimal()+
  labs(title= "National Average Seasonal Gas Price Trends", x="Dollars")+
  scale_y_continuous(limits = c(0, NA))

ggplotly(national_trend_polt)
```

```{r Seonsonal Cycle Plot, fig.width=13, fig.height=6}
ts_seasonal(ts_national, type="cycle", title="National Average: Monthly Cycle Trends")
```


```{r Seasonal Box Plot, fig.width=13, fig.height=6}
ts_seasonal(ts_national, type="box", title="National Average: Box Plot")
```



```{r Detrended Series, fig.width=13, fig.height=6}
ts_rollavg_detreend_national_df <- ts_national_df %>% 
  ungroup() %>% 
  mutate(lag = lag(monthly_average),
         lag2 = lag(monthly_average,2),
         lag3 = lag(monthly_average,3))%>% 
  filter(!is.na(lag3)) %>% 
  rowwise() %>% 
  mutate(lag_monthly_average = mean(c(lag,lag2,lag3))) %>% 
  mutate(detrend_val = monthly_average-lag_monthly_average)

ts_national_detrended <- ts(ts_rollavg_detreend_national_df %>% pull(detrend_val), start = c(2014, 6), frequency = 12)

national_trend_normed_plot <- ggseasonplot(ts_national_detrended)+
  theme_minimal()+
  labs(title= "National Average Seasonal Gas Price Detrended Series", x="Dollars")+
  scale_y_continuous(limits=c(-2,2))


ggplotly(national_trend_normed_plot)
```

```{r Polar Plot, fig.width=13, fig.height=6}
ggseasonplot(ts_national, polar=TRUE)+
  theme_minimal()+
  labs(title="Polar Plot: National Average")
```















